import { Criterion, University } from './types';

export const CRITERIA: Criterion[] = [
  { id: 'C1', name: 'Global Rank', type: 'cost', description: 'QS World University Ranking (Lower is better)' },
  { id: 'C2', name: 'Subject Rank', type: 'cost', description: 'Specific subject ranking (Lower is better)' },
  { id: 'C3', name: 'Tuition Fee', type: 'cost', description: 'Annual tuition in RMB' },
  { id: 'C4', name: 'Living Cost (CPI)', type: 'cost', description: 'City Price Index (Lower is cheaper)' },
  { id: 'C5', name: 'English Programs', type: 'benefit', description: 'Number of English-taught Master programs' },
  { id: 'C6', name: 'Intl. Environment', type: 'benefit', description: 'Percentage of international students' },
];

export const UNIVERSITIES: University[] = [
  {
    id: 'U1',
    name: 'Tsinghua University',
    city: 'Beijing',
    description: 'One of the most prestigious universities in China, known for engineering and computer science.',
    logoUrl: 'https://picsum.photos/100/100?random=1',
    rankGlobal: 14,
    rankSubject: 5,
    tuition: 30000,
    cpiIndex: 100,
    englishPrograms: 45,
    intlStudentPercent: 12,
    website: 'https://www.tsinghua.edu.cn',
  },
  {
    id: 'U2',
    name: 'Peking University',
    city: 'Beijing',
    description: 'A major research university in Beijing, famous for its beautiful campus and humanities programs.',
    logoUrl: 'https://picsum.photos/100/100?random=2',
    rankGlobal: 12,
    rankSubject: 8,
    tuition: 29000,
    cpiIndex: 100,
    englishPrograms: 38,
    intlStudentPercent: 14,
    website: 'https://www.pku.edu.cn',
  },
  {
    id: 'U3',
    name: 'Fudan University',
    city: 'Shanghai',
    description: 'Located in Shanghai, Fudan is known for its liberal atmosphere and strong business school.',
    logoUrl: 'https://picsum.photos/100/100?random=3',
    rankGlobal: 34,
    rankSubject: 20,
    tuition: 35000,
    cpiIndex: 110,
    englishPrograms: 50,
    intlStudentPercent: 10,
    website: 'https://www.fudan.edu.cn',
  },
  {
    id: 'U4',
    name: 'Zhejiang University',
    city: 'Hangzhou',
    description: 'A comprehensive research university with a strong focus on innovation and entrepreneurship.',
    logoUrl: 'https://picsum.photos/100/100?random=4',
    rankGlobal: 42,
    rankSubject: 15,
    tuition: 28000,
    cpiIndex: 85,
    englishPrograms: 30,
    intlStudentPercent: 9,
    website: 'https://www.zju.edu.cn',
  },
  {
    id: 'U5',
    name: 'Shanghai Jiao Tong University',
    city: 'Shanghai',
    description: 'Renowned for its medical school and engineering programs.',
    logoUrl: 'https://picsum.photos/100/100?random=5',
    rankGlobal: 46,
    rankSubject: 18,
    tuition: 32000,
    cpiIndex: 110,
    englishPrograms: 35,
    intlStudentPercent: 8,
    website: 'https://www.sjtu.edu.cn',
  },
  {
    id: 'U6',
    name: 'USTC',
    city: 'Hefei',
    description: 'University of Science and Technology of China, a haven for pure science research.',
    logoUrl: 'https://picsum.photos/100/100?random=6',
    rankGlobal: 94,
    rankSubject: 25,
    tuition: 25000,
    cpiIndex: 70,
    englishPrograms: 20,
    intlStudentPercent: 5,
    website: 'https://en.ustc.edu.cn',
  },
];

// Random Index for Consistency Check (n=1 to 10)
export const RANDOM_INDEX = [0, 0, 0.58, 0.9, 1.12, 1.24, 1.32, 1.41, 1.45, 1.49];